# Generated by Django 3.2.9 on 2021-12-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo/')),
                ('price', models.CharField(max_length=5, verbose_name='Цена')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
    ]
