# Generated by Django 3.2.9 on 2021-12-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211227_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='size',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.CharField(max_length=6, verbose_name='Цена')),
                ('img', models.ImageField(upload_to='products/', verbose_name='Фото (Обязательно)')),
                ('img2', models.ImageField(upload_to='products/', verbose_name='Фото (Не обязательно)')),
                ('img3', models.ImageField(upload_to='products/', verbose_name='Фото (Не обязательно)')),
                ('descript', models.TextField(default='Описание отсутствует', verbose_name='Описание (Не обязательно)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Категория')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.size', verbose_name='Размер')),
            ],
        ),
    ]
