# Generated by Django 3.2.9 on 2021-12-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211227_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Кафель', 'verbose_name_plural': 'Кафели'},
        ),
    ]
