# Generated by Django 3.2.9 on 2021-12-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Size_Product',
        ),
    ]
