# Generated by Django 3.2.9 on 2021-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211228_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото (Не обязательно)'),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото (Не обязательно)'),
        ),
    ]
