# Generated by Django 3.2.9 on 2021-12-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211229_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='products/no.jpeg', upload_to='category/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default='products/no.jpeg', upload_to='category/'),
        ),
    ]
