# Generated by Django 3.2.9 on 2021-12-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211229_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='products/no.jpeg', upload_to='category/', verbose_name='Фото (Не обязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='products/no.jpeg', upload_to='products/', verbose_name='Фото (Необязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.size_product', verbose_name='Размер (Не обязательно)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default='products/no.jpeg', upload_to='category/', verbose_name='Фото (Не обязательно)'),
        ),
    ]
